FROM hepcloud/decision-engine-ci
COPY entrypoint.sh /entrypoint.sh
#RUN groupadd -g 115 decision-engine-ci
#RUN useradd -u 1001 -g 115 decision-engine-ci
RUN groupadd -g 500 decision-engine-ci
RUN useradd -u 500 -g 500 decision-engine-ci
USER decision-engine-ci
ENTRYPOINT ["/entrypoint.sh"]
