{
 "title": "Metrics for counting slots and cores",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "DEM_HTCONDOR_CORES_HISTOGRAM",
   "type": "timeseries",
   "description": "Histogram of number of cores classified by State.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "dem_htcondor_cores_histogram_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", state=\"Claimed\"}",
     "legendFormat": "Claimed"
    },
    {
     "expr": "dem_htcondor_cores_histogram_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", state=\"Unclaimed\"}",
     "legendFormat": "Unclaimed"
    },
    {
     "expr": "dem_htcondor_cores_histogram_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", state=\"Owner\"}"
    },
    {
     "expr": "dem_htcondor_cores_histogram_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", state=\"Matched\"}"
    },
    {
     "expr": "dem_htcondor_cores_histogram_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", state=\"Preempting\"}"
    },
    {
     "expr": "dem_htcondor_cores_histogram_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", state=\"Backfill\"}"
    },
    {
     "expr": "dem_htcondor_cores_histogram_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", state=\"Drained\"}"
    }
   ]
  },
  {
   "title": "DEM_HTCONDOR_CORES_COUNT",
   "type": "timeseries",
   "description": "Number of cores classified by State.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (instance, job) (dem_htcondor_cores_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", state=\"Claimed\"})",
     "legendFormat": "Claimed"
    },
    {
     "expr": "sum by (instance, job) (dem_htcondor_cores_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", state=\"Unclaimed\"})",
     "legendFormat": "Unclaimed"
    },
    {
     "expr": "sum by (instance, job) (dem_htcondor_cores_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", state=\"Owner\"})",
     "legendFormat": "Owner"
    },
    {
     "expr": "sum by (instance, job) (dem_htcondor_cores_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", state=\"Matched\"})",
     "legendFormat": "Matched"
    },
    {
     "expr": "sum by (instance, job) (dem_htcondor_cores_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", state=\"Preempting\"})",
     "legendFormat": "Preempting"
    },
    {
     "expr": "sum by (instance, job) (dem_htcondor_cores_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", state=\"Backfill\"})",
     "legendFormat": "Backfill"
    },
    {
     "expr": "sum by (instance, job) (dem_htcondor_cores_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", state=\"Drained\"})",
     "legendFormat": "Drained"
    }
   ]
  },
  {
   "title": "DEM HTCONDOR JOBS STATUS COUNT",
   "type": "timeseries",
   "description": "Number of jobs classified per status (idle,running, removed, completed, held, transferring_output, suspended)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "\r\nsum by (instance, job) (dem_htcondor_jobs_status_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", job_status=\"1\"})",
     "legendFormat": "Idle"
    },
    {
     "expr": "\r\nsum by (instance, job) (dem_htcondor_jobs_status_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", job_status=\"2\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "\r\nsum by (instance, job) (dem_htcondor_jobs_status_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", job_status=\"3\"})",
     "legendFormat": "Removed"
    },
    {
     "expr": "\r\nsum by (instance, job) (dem_htcondor_jobs_status_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", job_status=\"4\"})",
     "legendFormat": "Completed"
    },
    {
     "expr": "\r\nsum by (instance, job) (dem_htcondor_jobs_status_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", job_status=\"5\"})",
     "legendFormat": "Held"
    },
    {
     "expr": "\r\nsum by (instance, job) (dem_htcondor_jobs_status_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", job_status=\"6\"})",
     "legendFormat": "Transferring_Output\t"
    },
    {
     "expr": "\r\nsum by (instance, job) (dem_htcondor_jobs_status_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", job_status=\"7\"})",
     "legendFormat": "Suspended"
    },
    {
     "expr": "\r\nsum by (instance, job) (dem_htcondor_jobs_status_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", job_status=\"0\"})",
     "legendFormat": "Unexpected"
    }
   ]
  },
  {
   "title": "DEM HTCONDOR SLOTS STATUS COUNT",
   "type": "timeseries",
   "description": "Number of glideins available for the client based on status.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "\r\nsum by (instance, job) (dem_htcondor_slots_status_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_status=\"Idle\"})",
     "legendFormat": "Idle"
    },
    {
     "expr": "\r\nsum by (instance, job) (dem_htcondor_slots_status_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_status=\"Busy\"})",
     "legendFormat": "Busy"
    },
    {
     "expr": "\r\nsum by (instance, job) (dem_htcondor_slots_status_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_status=\"Retiring\"})",
     "legendFormat": "Retiring"
    },
    {
     "expr": "\r\nsum by (instance, job) (dem_htcondor_slots_status_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_status=\"Vacating\"})",
     "legendFormat": "Vacating"
    },
    {
     "expr": "\r\nsum by (instance, job) (de_m_source_status_gauge{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_status=\"Suspended\"})",
     "legendFormat": "Suspended"
    },
    {
     "expr": "\r\nsum by (instance, job) (dem_htcondor_slots_status_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_status=\"Benchmarking\"})",
     "legendFormat": "Benchmarking"
    },
    {
     "expr": "\r\nsum by (instance, job) (dem_htcondor_slots_status_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_status=\"Killing\"})",
     "legendFormat": "Killing"
    },
    {
     "expr": "\r\nsum by (instance, job) (dem_htcondor_slots_status_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_status=\"None\"})",
     "legendFormat": "None"
    }
   ]
  }
 ]
}