{
 "title": "Redis Health and Information",
 "description": "Redis Dashboard for Prometheus Redis Exporter 1.x",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(redis_up, namespace)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(redis_up{namespace=~\"$namespace\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Max Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{instance=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_connected_clients{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(100 * (redis_memory_used_bytes{instance=~\"$instance\"}  / redis_memory_max_bytes{instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Total Commands / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{instance=~\"$instance\"} [1m])) by (cmd)",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "used, {{ instance }}"
    },
    {
     "expr": "redis_memory_max_bytes{instance=~\"$instance\"}",
     "legendFormat": "max, {{ instance }}"
    }
   ]
  },
  {
   "title": "Total Time Spent by Command / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_commands_duration_seconds_total{instance=~\"$instance\"}[1m])) by (cmd) != 0",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Average Time Spent by Command / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_commands_duration_seconds_total{instance =~ \"$instance\"}[1m])) by (cmd)\n  /\nsum(irate(redis_commands_total{instance =~ \"$instance\"}[1m])) by (cmd)\n",
     "legendFormat": "{{ cmd }}"
    }
   ]
  }
 ]
}