{
 "title": "Runtime for Transform, Logic Engine, Publisher, Source",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Transform",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(de_transform_run_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}[5m])) ",
     "legendFormat": "de_transform"
    }
   ]
  },
  {
   "title": "Transform Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "de_transform_run_seconds_sum\r\n{channel_name=\"resource_request\", instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", transform_name=\"JobClustering\"}/(de_transform_run_seconds_count\r\n{channel_name=\"resource_request\", instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", transform_name=\"JobClustering\"})",
     "legendFormat": "JobClustering"
    },
    {
     "expr": "de_transform_run_seconds_sum{channel_name=\"test_channel\", instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", transform_name=\"TransformNOP\"}/(de_transform_run_seconds_count{channel_name=\"test_channel\", instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", transform_name=\"TransformNOP\"})",
     "legendFormat": "TransformNOP"
    },
    {
     "expr": "de_transform_run_seconds_sum{channel_name=\"resource_request\", instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", transform_name=\"GlideinRequestManifests\"}/(de_transform_run_seconds_count{channel_name=\"resource_request\", instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", transform_name=\"GlideinRequestManifests\"})",
     "legendFormat": "GlideinRequestManifests"
    },
    {
     "expr": "de_transform_run_seconds_sum\r\n{channel_name=\"resource_request\", instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", transform_name=\"GridFigureOfMerit\"}/(de_transform_run_seconds_count\r\n{channel_name=\"resource_request\", instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", transform_name=\"GridFigureOfMerit\"})",
     "legendFormat": "GridFigureOfMerit"
    }
   ]
  },
  {
   "title": "Transform Average JobClustering",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "de_transform_run_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", transform_name=\"JobClustering\"}/(de_transform_run_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", transform_name=\"JobClustering\"})",
     "legendFormat": "JobClustering"
    }
   ]
  },
  {
   "title": "Transform Averge GlideinRequestManifests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "de_transform_run_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\",  transform_name=\"GlideinRequestManifests\"}/(de_transform_run_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\",  transform_name=\"GlideinRequestManifests\"})",
     "legendFormat": "GlideinRequestManifests"
    }
   ]
  },
  {
   "title": "Transform Average GridFigureOrMerit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "de_transform_run_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", transform_name=\"GridFigureOfMerit\"}/(de_transform_run_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", transform_name=\"GridFigureOfMerit\"})",
     "legendFormat": "GridFigureOrMerit"
    }
   ]
  },
  {
   "title": "Transform TransformNOP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "de_transform_run_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", transform_name=\"TransformNOP\"}/(de_transform_run_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", transform_name=\"TransformNOP\"})",
     "legendFormat": "TransformNOP"
    }
   ]
  },
  {
   "title": "Logic Engine Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "de_logicengine_run_seconds_sum{channel_name=\"resource_request\", instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", logicengine_name=\"LogicEngine\"}/(de_logicengine_run_seconds_count{channel_name=\"resource_request\", instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", logicengine_name=\"LogicEngine\"})",
     "legendFormat": "Resource Request"
    },
    {
     "expr": "de_logicengine_run_seconds_sum{channel_name=\"test_channel\", instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", logicengine_name=\"LogicEngine\"}/(de_logicengine_run_seconds_count{channel_name=\"test_channel\", instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", logicengine_name=\"LogicEngine\"})",
     "legendFormat": "Test Channel"
    }
   ]
  },
  {
   "title": "Logic Engine",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(de_logicengine_run_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}[5m])) ",
     "legendFormat": "Logic Engine"
    }
   ]
  },
  {
   "title": "Logic Engine Average Resource Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "de_logicengine_run_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\",channel_name=\"resource_request\"}/(de_logicengine_run_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", channel_name=\"resource_request\"})",
     "legendFormat": "Resource Request"
    }
   ]
  },
  {
   "title": "Logic Engine Average Test Channel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "de_logicengine_run_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\",channel_name=\"test_channel\"}/(de_logicengine_run_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\",channel_name=\"test_channel\"})",
     "legendFormat": "Test Channel"
    }
   ]
  },
  {
   "title": "Publisher",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(de_publisher_run_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}[5m])) ",
     "legendFormat": "Publisher"
    }
   ]
  },
  {
   "title": "Publisher Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "de_publisher_run_seconds_sum{channel_name=\"resource_request\", instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", publisher_name=\"GlideClientGlobalManifests\"}/(de_publisher_run_seconds_count{channel_name=\"resource_request\", instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", publisher_name=\"GlideClientGlobalManifests\"})",
     "legendFormat": "GlideClientGlobalManifests"
    },
    {
     "expr": "de_publisher_run_seconds_sum\r\n{channel_name=\"resource_request\", instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", publisher_name=\"GlideinWMSManifests\"}/(de_publisher_run_seconds_count\r\n{channel_name=\"resource_request\", instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", publisher_name=\"GlideinWMSManifests\"})",
     "legendFormat": "GlideinWMSManifests"
    },
    {
     "expr": "de_publisher_run_seconds_sum\r\n{channel_name=\"test_channel\", instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", publisher_name=\"PublisherNOP\"}/(de_publisher_run_seconds_count\r\n{channel_name=\"test_channel\", instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", publisher_name=\"PublisherNOP\"})",
     "legendFormat": "PublisherNOP"
    }
   ]
  },
  {
   "title": "Publisher Average PublisherNOP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "de_publisher_run_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\",publisher_name=\"PublisherNOP\"}/(de_publisher_run_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\",publisher_name=\"PublisherNOP\"})",
     "legendFormat": "PublisherNOP"
    }
   ]
  },
  {
   "title": "Publisher Average GlideinWMSManifests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "de_publisher_run_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\",publisher_name=\"GlideinWMSManifests\"}/(de_publisher_run_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\",publisher_name=\"GlideinWMSManifests\"})",
     "legendFormat": "GlideinWMSManifests"
    }
   ]
  },
  {
   "title": "Publisher Average GlideClientGlobalManifests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "de_publisher_run_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\",publisher_name=\"GlideClientGlobalManifests\"}/(de_publisher_run_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\",publisher_name=\"GlideClientGlobalManifests\"})",
     "legendFormat": "GlideClientGlobalManifests"
    }
   ]
  },
  {
   "title": "Source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum(rate(de_source_acquire_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\"}[5m])) ",
     "legendFormat": "Source"
    }
   ]
  },
  {
   "title": "Source Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "de_source_acquire_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"FactoryEntriesSource\"}/(de_source_acquire_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"FactoryEntriesSource\"})",
     "legendFormat": "FactoryEntriesSource"
    },
    {
     "expr": "de_source_acquire_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"Factory_Entries\"}/(de_source_acquire_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"Factory_Entries\"})",
     "legendFormat": "Factory Entries"
    },
    {
     "expr": "de_source_acquire_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"FigureOfMerit\"}/(de_source_acquire_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"FigureOfMerit\"})",
     "legendFormat": "FigureOfMerit"
    },
    {
     "expr": "de_source_acquire_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"GceFigureOfMerit\"}\r\n/(de_source_acquire_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"GceFigureOfMerit\"}\r\n)",
     "legendFormat": "GceFigureOfMerit"
    },
    {
     "expr": "de_source_acquire_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"NerscFigureOfMerit\"}\r\n/(de_source_acquire_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"NerscFigureOfMerit\"}\r\n)",
     "legendFormat": "NerscFigureOfMerit"
    },
    {
     "expr": "de_source_acquire_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"StartdManifestsSource\"}/(de_source_acquire_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"StartdManifestsSource\"})",
     "legendFormat": "StartdManifestsSource"
    },
    {
     "expr": "de_source_acquire_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"factoryglobal_manifests\"}/(de_source_acquire_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"factoryglobal_manifests\"})",
     "legendFormat": "factoryglobal_manifests"
    },
    {
     "expr": "de_source_acquire_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"jobs_manifests\"}\r\n/(de_source_acquire_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"jobs_manifests\"}\r\n)",
     "legendFormat": "jobs_manifests"
    },
    {
     "expr": "de_source_acquire_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"source1\"}/(de_source_acquire_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"source1\"})",
     "legendFormat": "source1"
    }
   ]
  },
  {
   "title": "Source Average factoryglobal_manifests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "de_source_acquire_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"factoryglobal_manifests\"}/(de_source_acquire_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"factoryglobal_manifests\"})",
     "legendFormat": "factoryglobal_manifests"
    }
   ]
  },
  {
   "title": "Source Average FigureOfMerit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "de_source_acquire_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"FigureOfMerit\"}/(de_source_acquire_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"FigureOfMerit\"})",
     "legendFormat": "FigureOfMerit"
    }
   ]
  },
  {
   "title": "Source Average source1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "de_source_acquire_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"source1\"}/(de_source_acquire_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"source1\"})",
     "legendFormat": "source1"
    }
   ]
  },
  {
   "title": "Source Average NerscFigureOfMerit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "de_source_acquire_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"NerscFigureOfMerit\"}/(de_source_acquire_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"NerscFigureOfMerit\"})",
     "legendFormat": "NerscFigureOfMerit"
    }
   ]
  },
  {
   "title": "Source Average jobs_manifests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "de_source_acquire_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"jobs_manifests\"}/(de_source_acquire_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"jobs_manifests\"})",
     "legendFormat": "jobs_manifests"
    }
   ]
  },
  {
   "title": "Source Average Factory Entries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "de_source_acquire_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"Factory_Entries\"}/(de_source_acquire_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"Factory_Entries\"})",
     "legendFormat": "Factory Entries"
    }
   ]
  },
  {
   "title": "Source Average FactoryEntriesSource",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "de_source_acquire_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"FactoryEntriesSource\"}/(de_source_acquire_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"FactoryEntriesSource\"})",
     "legendFormat": "FactoryEntriesSource"
    }
   ]
  },
  {
   "title": "Source Average GceFigureOfMerit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "targets": [
    {
     "expr": "de_source_acquire_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"GceFigureOfMerit\"}/(de_source_acquire_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"GceFigureOfMerit\"})",
     "legendFormat": "GceFigureOfMerit"
    }
   ]
  },
  {
   "title": "Source Average StartdManifestsSource",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "de_source_acquire_seconds_sum{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"StartdManifestsSource\"}/(de_source_acquire_seconds_count{instance=\"fermicloud857.fnal.gov:8000\", job=\"decisionengine-dev-ilyab\", source_name=\"StartdManifestsSource\"})",
     "legendFormat": "StartdManifestsSource"
    }
   ]
  }
 ]
}