on: [pull_request, push]

jobs:
  pylint_job:
    runs-on: ubuntu-latest
    name: A job to run the pep8 checks
    strategy:
      matrix:
        pyver: ["2.7", "3.6"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: 'decisionengine_modules'
        id: checkout
      - name: pep8 action step
        uses: ./.github/actions/pep8-in-sl7-docker
        id: pep8
        with:
          PYVER: ${{ matrix.pyver }}
      - name: Archive reports
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: logs-${{ matrix.pyver }}.tar.bz2
