on: [pull_request]

jobs:
  pylint_job:
    runs-on: ubuntu-latest
    name: A job to run the pylint script
    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: 'decisionengine_modules'
      id: checkout
    - name: Cache venv
      uses: actions/cache@v1
      with:
        path: ./venv
        key: ${{ runner.os }}-venv-
        restore-keys: |
            ${{ runner.os }}-venv-
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ./dependencies
        key: ${{ runner.os }}-dependencies-
        restore-keys: |
            ${{ runner.os }}-dependencies-
    - name: pylint action step
      uses: ./.github/actions/pylint-in-sl7-docker
      id: pylint
    - name: Archive reports
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: reports
        path: logs.tar.bz2
